imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    secret: '%secret%'
    default_locale: '%locale%'
    php_errors:
        log: true

wse_cli:
  stream_recorder:
    applicationName: "worship"
