# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
  wse.apiCallBuilder:
    class: Services\ApiCallBuilder
  wse.apiCall:
    class: ApiCall
    factory: 'wse.apiCallBuilder:CreateApiCall'
    arguments: ['%wse.hostname%','%wse.authMethod%','%wse.username%','%wse.password%']